blueprint:
  name: Remotec ZRC-90 Scene Master
  description: Create an automation for the Remotec ZRC-90 8 button remote using ZWAVE-JS integration
  domain: automation
  input:
    remotec_zrc90:
      name: Remotec ZRC-90
      description: The Remotec ZRC-90 to interact with.
      selector:
        device:
          filter:
            integration: zwave_js
            manufacturer: Remotec
            model: BW8510
    button_1_1:
      name: Press Button 1 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
    button_1_2:
      name: Press Button 1 2x
      description: Action to run on button press twice.
      default: []
      selector:
        action: {}
    button_1_held:
      name: Hold Button 1
      description: Action to run on button hold. (Fires multiple times when held)
      default: []
      selector:
        action: {}
    button_1_hold_release:
      name: Hold & Release Button 1
      description: Action to run on button hold on release. (Doesn't trigger multiple times)
      default: []
      selector:
        action: {}
    button_2_1:
      name: Press Button 2 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
    button_2_2:
      name: Press Button 2 2x
      description: Action to run on button press twice.
      default: []
      selector:
        action: {}
    button_2_held:
      name: Hold Button 2
      description: Action to run on button hold. (Fires multiple times when held)
      default: []
      selector:
        action: {}
    button_2_hold_release:
      name: Hold & Release Button 2
      description: Action to run on button hold on release. (Doesn't trigger multiple times)
      default: []
      selector:
        action: {}
    button_3_1:
      name: Press Button 3 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
    button_3_2:
      name: Press Button 3 2x
      description: Action to run on button press twice.
      default: []
      selector:
        action: {}
    button_3_held:
      name: Hold Button 3
      description: Action to run on button hold. (Fires multiple times when held)
      default: []
      selector:
        action: {}
    button_3_hold_release:
      name: Hold & Release Button 3
      description: Action to run on button hold on release. (Doesn't trigger multiple times)
      default: []
      selector:
        action: {}
    button_4_1:
      name: Press Button 4 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
    button_4_2:
      name: Press Button 4 2x
      description: Action to run on button press twice.
      default: []
      selector:
        action: {}
    button_4_held:
      name: Hold Button 4
      description: Action to run on button hold. (Fires multiple times when held)
      default: []
      selector:
        action: {}
    button_4_hold_release:
      name: Hold & Release Button 4
      description: Action to run on button hold on release. (Doesn't trigger multiple times)
      default: []
      selector:
        action: {}
    button_5_1:
      name: Press Button 5 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
    button_5_2:
      name: Press Button 5 2x
      description: Action to run on button press twice.
      default: []
      selector:
        action: {}
    button_5_held:
      name: Hold Button 5
      description: Action to run on button hold. (Fires multiple times when held)
      default: []
      selector:
        action: {}
    button_5_hold_release:
      name: Hold & Release Button 5
      description: Action to run on button hold on release. (Doesn't trigger multiple times)
      default: []
      selector:
        action: {}
    button_6_1:
      name: Press Button 6 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
    button_6_2:
      name: Press Button 6 2x
      description: Action to run on button press twice.
      default: []
      selector:
        action: {}
    button_6_held:
      name: Hold Button 6
      description: Action to run on button hold. (Fires multiple times when held)
      default: []
      selector:
        action: {}
    button_6_hold_release:
      name: Hold & Release Button 6
      description: Action to run on button hold on release. (Doesn't trigger multiple times)
      default: []
      selector:
        action: {}
    button_7_1:
      name: Press Button 7 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
    button_7_2:
      name: Press Button 7 2x
      description: Action to run on button press twice.
      default: []
      selector:
        action: {}
    button_7_held:
      name: Hold Button 7
      description: Action to run on button hold. (Fires multiple times when held)
      default: []
      selector:
        action: {}
    button_7_hold_release:
      name: Hold & Release Button 7
      description: Action to run on button hold on release. (Doesn't trigger multiple times)
      default: []
      selector:
        action: {}
    button_8_1:
      name: Press Button 8 1x
      description: Action to run on button press once.
      default: []
      selector:
        action: {}
    button_8_2:
      name: Press Button 8 2x
      description: Action to run on button press twice.
      default: []
      selector:
        action: {}
    button_8_held:
      name: Hold Button 8
      description: Action to run on button hold. (Fires multiple times when held)
      default: []
      selector:
        action: {}
    button_8_hold_release:
      name: Hold & Release Button 8
      description: Action to run on button hold on release. (Doesn't trigger multiple times)
      default: []
      selector:
        action: {}

mode: single

max_exceeded: silent

trigger:
  platform: event
  event_type: zwave_js_value_notification
  event_data:
    command_class_name: Central Scene
    device_id: !input remotec_zrc90
action:
  - variables:
      scene_id: "{{ trigger.event.data.property_key_name }}"
      scene_value_id: "{{ trigger.event.data.value }}"

  - choose:
      - conditions:
        - "{{ scene_id == '001' }}"
        - "{{ scene_value_id == 'KeyPressed' or scene_value_id == '0' }}"
        sequence: !input button_1_1
      - conditions:
        - "{{ scene_id == '001' }}"
        - "{{ scene_value_id == 'KeyPressed2x' or scene_value_id == '3' }}"
        sequence: !input button_1_2
      - conditions:
        - "{{ scene_id == '001' }}"
        - "{{ scene_value_id == 'KeyHeldDown' }}"
        sequence: !input button_1_held
      - conditions:
        - "{{ scene_id == '001' }}"
        - "{{ scene_value_id == 'KeyReleased' }}"
        sequence: !input button_1_hold_release
      - conditions:
        - "{{ scene_id == '002' }}"
        - "{{ scene_value_id == 'KeyPressed' or scene_value_id == '0' }}"
        sequence: !input button_2_1
      - conditions:
        - "{{ scene_id == '002' }}"
        - "{{ scene_value_id == 'KeyPressed2x' or scene_value_id == '3' }}"
        sequence: !input button_2_2
      - conditions:
        - "{{ scene_id == '002' }}"
        - "{{ scene_value_id == 'KeyHeldDown' }}"
        sequence: !input button_2_held
      - conditions:
        - "{{ scene_id == '002' }}"
        - "{{ scene_value_id == 'KeyReleased' }}"
        sequence: !input button_2_hold_release
      - conditions:
        - "{{ scene_id == '003' }}"
        - "{{ scene_value_id == 'KeyPressed' or scene_value_id == '0' }}"
        sequence: !input button_3_1
      - conditions:
        - "{{ scene_id == '003' }}"
        - "{{ scene_value_id == 'KeyPressed2x' or scene_value_id == '3' }}"
        sequence: !input button_3_2
      - conditions:
        - "{{ scene_id == '003' }}"
        - "{{ scene_value_id == 'KeyHeldDown' }}"
        sequence: !input button_3_held
      - conditions:
        - "{{ scene_id == '003' }}"
        - "{{ scene_value_id == 'KeyReleased' }}"
        sequence: !input button_3_hold_release
      - conditions:
        - "{{ scene_id == '004' }}"
        - "{{ scene_value_id == 'KeyPressed' or scene_value_id == '0' }}"
        sequence: !input button_4_1
      - conditions:
        - "{{ scene_id == '004' }}"
        - "{{ scene_value_id == 'KeyPressed2x' or scene_value_id == '3' }}"
        sequence: !input button_4_2
      - conditions:
        - "{{ scene_id == '004' }}"
        - "{{ scene_value_id == 'KeyHeldDown' }}"
        sequence: !input button_4_held
      - conditions:
        - "{{ scene_id == '004' }}"
        - "{{ scene_value_id == 'KeyReleased' }}"
        sequence: !input button_4_hold_release
      - conditions:
        - "{{ scene_id == '005' }}"
        - "{{ scene_value_id == 'KeyPressed' or scene_value_id == '0' }}"
        sequence: !input button_5_1
      - conditions:
        - "{{ scene_id == '005' }}"
        - "{{ scene_value_id == 'KeyPressed2x' or scene_value_id == '3' }}"
        sequence: !input button_5_2
      - conditions:
        - "{{ scene_id == '005' }}"
        - "{{ scene_value_id == 'KeyHeldDown' }}"
        sequence: !input button_5_held
      - conditions:
        - "{{ scene_id == '005' }}"
        - "{{ scene_value_id == 'KeyReleased' }}"
        sequence: !input button_5_hold_release
      - conditions:
        - "{{ scene_id == '006' }}"
        - "{{ scene_value_id == 'KeyPressed' or scene_value_id == '0' }}"
        sequence: !input button_6_1
      - conditions:
        - "{{ scene_id == '006' }}"
        - "{{ scene_value_id == 'KeyPressed2x' or scene_value_id == '3' }}"
        sequence: !input button_6_2
      - conditions:
        - "{{ scene_id == '006' }}"
        - "{{ scene_value_id == 'KeyHeldDown' }}"
        sequence: !input button_6_held
      - conditions:
        - "{{ scene_id == '006' }}"
        - "{{ scene_value_id == 'KeyReleased' }}"
        sequence: !input button_6_hold_release
      - conditions:
        - "{{ scene_id == '007' }}"
        - "{{ scene_value_id == 'KeyPressed' or scene_value_id == '0' }}"
        sequence: !input button_7_1
      - conditions:
        - "{{ scene_id == '007' }}"
        - "{{ scene_value_id == 'KeyPressed2x' or scene_value_id == '3' }}"
        sequence: !input button_7_2
      - conditions:
        - "{{ scene_id == '007' }}"
        - "{{ scene_value_id == 'KeyHeldDown' }}"
        sequence: !input button_7_held
      - conditions:
        - "{{ scene_id == '007' }}"
        - "{{ scene_value_id == 'KeyReleased' }}"
        sequence: !input button_7_hold_release
      - conditions:
        - "{{ scene_id == '008' }}"
        - "{{ scene_value_id == 'KeyPressed' or scene_value_id == '0' }}"
        sequence: !input button_8_1
      - conditions:
        - "{{ scene_id == '008' }}"
        - "{{ scene_value_id == 'KeyPressed2x' or scene_value_id == '3' }}"
        sequence: !input button_8_2
      - conditions:
        - "{{ scene_id == '008' }}"
        - "{{ scene_value_id == 'KeyHeldDown' }}"
        sequence: !input button_8_held
      - conditions:
        - "{{ scene_id == '008' }}"
        - "{{ scene_value_id == 'KeyReleased' }}"
        sequence: !input button_8_hold_release
